# An Alternate Universe

In an alternate universe there exists a language named Clojure that makes programming complex things enjoyable and fun.  It has a very strong functional background and lots of great libraries and some intelligent users.  In that universe, it enjoys the popularity it deserves and has all the great things written for you.


In this universe, we can do basic statistical analysis and we can easily write extensions to the system we are working with in the language we like, they run instantly and create joy.  Let's take a short walk through that universe.

## A Short Digression: Clojure

Clojure is an implementation and redesign of lisp that runs on the jvm.  It being a lisp means that it is homoiconic, or that programs in clojure are expressed in the datastructures of clojure.  Many great minds have worked to design this modern lisp and it has an extremely well though out basic foundation.   

LISP as a language was designed first written about by John Mccarthy in 1955.  You can find some interesting information about it [here](http://www.paulgraham.com/rootsoflisp.html).  It was the first language with garbage collection and also was the first high level language assuming you do not believe that fortran is a high level language.

Let's take a second and familiarize with things here.

In [1]:
;; The language is described using its datastructures...

;; This is a list:

(list 1 2 3)

(1 2 3)

In [2]:
;; This is also a list

'(1 2 3)

(1 2 3)

In [3]:
;; Lists can be executed.  If the reader finds a list that isn't 'escaped'
;; it will ask the compiler to output code to execute the expression.

(+ 1 2 3)

6

In [4]:
;; Vectors in clojure are functional datastructures
;; that have very good random access semantics.

[1 2 3 4]

[1 2 3 4]

In [35]:
;; They can work like functions

([4 1 3 2] 0)

4

In [36]:
;; Keywords are global constants, like names and they start with a ':'

:one

:one

In [37]:
;; Maps (functional equivalent of a dict) are curly braced:

{:a 1 :b 2}

{:a 1, :b 2}

In [41]:
;; You can find things in maps lots of ways, but maps with keyword keys are
;; more special than other maps.

;; Retrieving the value stored under key 'one'
(println (get {"one" 1 "two" 2} "one"))

;; Retrieving the value stored under the keyword key :one, we can use the
;; function syntax.
(:one {:one "hi" :two "bye"})

1


"hi"

In [7]:
;; If you add something to a vector or a map, you get a new map that 
;; shares structure with the previous item.  This means the previous 
;; item is unchanged

(def first-list [1 2 3 4])

(println (conj first-list 5))
(println (assoc first-list 0 6))
first-list

[1 2 3 4 5]
[6 2 3 4]


[1 2 3 4]

In the interests of time, we have to move on.  I hoped you liked our small intro and it allows the next section to be perhaps less mysterious

In [2]:
;;Grab the big things we will be using.
(require '[clojupyter.misc.helper :as helper])
;;these are order dependent because oz indirectly includes jna 3.2.2 and 
;; tech.jna requires jna 5.0.0
(helper/add-dependencies '[techascent/tech.ml "0.27"])
(helper/add-dependencies '[metasoarous/oz "1.6.0-alpha2"])
(helper/add-dependencies '[cnuernber/garmin-fit-clj "0.1"])
(require '[cemerick.pomegranate :as pg])

;;We need the fit jar to make this all work.
(pg/add-classpath "resources/fit.jar")

;;You didn't want to see that output anyway, trust me...
:ok

:ok

In [20]:
(require '[cnuernber.garmin-fit :as fit])
(require '[tech.ml.dataset :as ds])
(require '[tech.ml.dataset.column :as ds-col])
(require '[tech.ml.dataset.etl :as etl])
(require '[tech.compute.tensor.functional :as tens-fun])
(require '[clojure.core.matrix :as m])
(require '[clojure.set :as c-set])
(require '[clojure.pprint :as pp])
(require '[oz.notebook.clojupyter :as oz])
(import '[java.time Duration])


java.time.Duration

## Sequences

We load the data.  This produces a datastructure called a sequence.  This is similar to a singly-linked list but it isn't constructed of nodes.  It is a functional datastructure, however, and we can manipulate it in various ways.
The file is a sequence of maps and the `:event-type` member of each map tells you what you are looking at.  One thing to note is that sequences are lazy so this doesn't load the entire file.  It loads only what you are looking at.

In [22]:
(def test-fname "data/activities/81623728.fit.gz")

(pp/pprint (take 6 (fit/decode test-fname)))

({:event-type :file-id,
  :message-type 4,
  :manufacturer 1,
  :product 1036,
  :serial-number 3824793667,
  :number nil}
 {:event-type :device-info,
  :batter-status :invalid,
  :timestamp
  #object[com.garmin.fit.DateTime 0x7befbf9 "Sat Aug 10 08:15:33 MDT 2013"]}
 {:event-type :device-info,
  :batter-status :invalid,
  :timestamp
  #object[com.garmin.fit.DateTime 0x5c7034cc "Sat Aug 10 08:15:33 MDT 2013"]}
 {:event-type :device-info,
  :batter-status :invalid,
  :timestamp
  #object[com.garmin.fit.DateTime 0x2cba03d0 "Sat Aug 10 08:15:33 MDT 2013"]}
 {:event-type :device-info,
  :batter-status :invalid,
  :timestamp
  #object[com.garmin.fit.DateTime 0x5f4fa4ea "Sat Aug 10 08:15:33 MDT 2013"]}
 {:position-lat [477708398],
  :enhanced-altitude [1676.0],
  :speed [1.774],
  :position-long [-1256056043],
  :cadence [52],
  :power [96],
  :enhanced-speed [1.774],
  :distance [0.0],
  :timestamp [745078623],
  :altitude [1676.0],
  :event-type :record-message,
  :temperature [20]})


nil

## Functions

We now define our first function.  It takes a filename and produces a dataset consisting of records of a given type.  The dataset system knows how to take a sequence of maps (what we produced above) and translate those maps into a column-major dataset object that stores the column data efficiently.  We do have to make sure the values in each map are scalars which they should be logically for this dataset.

In [23]:
(defn fit-file->dataset
  [fname]
  (ds/->dataset
   (->> (fit/decode fname)
        (filter #(= :record-message (:event-type %)))
        (map (fn [record-data]
               (->> (dissoc record-data :event-type)
                    (map (fn [[k v]]
                           [k (if (sequential? v)
                                (first v)
                                v)]))
                    (into {})))))
   {:table-name fname}))


(defonce test-ds (fit-file->dataset fit/test-fname))


(ds/select test-ds :all (range 5))

data/activities/81623728.fit.gz [5 11]:

| :position-lat | :enhanced-altitude | :speed | :position-long | :cadence | :power | :enhanced-speed | :distance | :timestamp | :altitude | :temperature |
|---------------+--------------------+--------+----------------+----------+--------+-----------------+-----------+------------+-----------+--------------|
|     477708398 |           1676.000 |  1.774 |    -1256056043 |       52 |     96 |           1.774 |     0.000 |  745078623 |  1676.000 |           20 |
|     477708561 |           1676.000 |  1.774 |    -1256056241 |       52 |    234 |           1.774 |     1.770 |  745078624 |  1676.000 |           20 |
|     477708741 |           1676.000 |  2.272 |    -1256056574 |       46 |    220 |           2.272 |     4.050 |  745078625 |  1676.000 |           20 |
|     477708850 |           1676.000 |  2.112 |    -1256056828 |       30 |    220 |           2.112 |     6.160 |  745078626 |  1676.000 |           20 |
|     477709093 |           1

## Moar Functions!!

1. We have to do a bit of dataset processing.  For this dataset we choose to just drop any rows with missing data.
2. Next we have a function to find the overall duration of the dataset which is expressed as `(- (max :timestamp) (min :timestamp))` 
3.  Some work to convert from semicircular coordinates to lat-lon and get into the pipeline options that we run the dataset through.

In [24]:
(defn drop-missing
  [dataset]
  (let [missing-indexes (->> (ds/columns-with-missing-seq dataset)
                             (mapcat (fn [{:keys [column-name]}]
                                       (-> (ds/column dataset column-name)
                                           ds-col/missing)))
                             set)]
    (ds/select dataset :all  (->> (range (second (m/shape dataset)))
                                  (remove missing-indexes)))))


(defn ds-duration
  "Duration in seconds of the entire ride."
  [dataset]
  (let [{act-min :min
         act-max :max}
        (-> (ds/column dataset :timestamp)
            (ds-col/stats [:min :max]))]
    (Duration/ofSeconds
     (- (long act-max) (long act-min)))))

(def semi->deg
  (/ 180.0
     (Math/pow 2 31)))


(def lat-lon [:position-lat :position-long] )


(def load-pipeline
  [['m= lat-lon '(* (col) 8.381903171539307E-8)]
   '[m= :altitude-norm (/ (- (col :altitude) (min (col :altitude)))
                          (- (max (col :altitude)) (min (col :altitude))))]
   '[m= :speed-mph (* (col :speed) 2.23694)]])


(defn run-pipeline
  [dataset & {:keys [target] :as options}]
  (-> (drop-missing dataset)
      (etl/apply-pipeline load-pipeline options)
      :dataset
      ;;Make handling the data in the browser sane.
      (#(ds/ds-take-nth 10 %))
      (etl/apply-pipeline '[[m= :speed-avg (rolling 20 :mean (col :speed-mph))]
                            [m= :power-avg (rolling 20 :mean (col :power))]
                            [m= :cadence-avg (rolling 20 :mean (col :cadence))]
                            [m= :minutes-from-start (/ (- (col :timestamp)
                                                          (min (col :timestamp)))
                                                       60)]]
                          {})))



#'user/run-pipeline

## Run The Functions!!

We now process the dataset and produce a new dataset.  Dataset processing is functional so processing a column produces a new column.  Processing a dataset producess...Well, a few things.  One of them is a new dataset.

Another is a new pipeline with the intermediate values calculated embedded datastructure.  So you can use the produced pipeline in production without having to reengineer it.

In [25]:
(def processed-pipeline (run-pipeline test-ds))

(def processed-ds (:dataset processed-pipeline))

(ds/select processed-ds :all (range 5))

data/activities/81623728.fit.gz [5 17]:

| :position-lat | :enhanced-altitude | :speed | :position-long | :cadence |  :power | :enhanced-speed | :distance |    :timestamp | :altitude | :temperature | :altitude-norm | :speed-mph | :speed-avg | :power-avg | :cadence-avg | :minutes-from-start |
|---------------+--------------------+--------+----------------+----------+---------+-----------------+-----------+---------------+-----------+--------------+----------------+------------+------------+------------+--------------+---------------------|
|        40.041 |           1676.000 |  1.774 |       -105.281 |   52.000 |  96.000 |           1.774 |     0.000 | 745078623.000 |  1676.000 |       20.000 |          0.000 |      3.968 |      3.987 |     75.550 |       42.450 |               0.000 |
|        40.041 |           1676.000 |  2.581 |       -105.282 |   37.000 | 121.000 |           2.581 |    24.840 | 745078633.000 |  1676.000 |       20.000 |          0.000 |      5.774 |      3.961 |  

## That Was Great!  Now What?

We take our dataset object and convert it back into a sequence of maps.  Sequences of maps are something that clojure's core algorithm facilities handle robustly so if we can we would like to be speaking in that language.

In [27]:
(def all-the-data (-> (ds/select processed-ds
                                 (concat lat-lon
                                         [:timestamp :altitude :power :speed-mph
                                          :minutes-from-start
                                          :cadence :power-avg :speed-avg :cadence-avg])
                                 :all)
                      (ds/->flyweight)))

(pp/pprint (first all-the-data))

{:position-lat 40.041055362671614,
 :speed-avg 3.986898205092907,
 :speed-mph 3.968331668798924,
 :cadence-avg 42.45,
 :position-long -105.28140130452812,
 :cadence 52.0,
 :power 96.0,
 :power-avg 75.55,
 :timestamp 7.45078623E8,
 :minutes-from-start 0.0,
 :altitude 1676.0}


nil

At this point we calculate some intermediate values which we will use when visualizing the data.

In [26]:
(def timestamp-data (ds-col/stats (ds/column processed-ds :timestamp)
                                  [:min :max]))

(def minutes-range (ds-col/stats (ds/column processed-ds :minutes-from-start)
                                  [:min :max]))

(def altitude-data (ds-col/stats (ds/column processed-ds
                                            :altitude)
                                 [:min :max]))

(def latitude-range (mapv (ds-col/stats (ds/column processed-ds :position-lat)
                                        [:min :max])
                          [:min :max]))

(def longitude-range (mapv (ds-col/stats (ds/column processed-ds :position-long)
                                         [:min :max])
                           [:min :max]))

(pp/pprint [timestamp-data minutes-range altitude-data])

[{:min 7.45078623E8, :max 7.45088532E8}
 {:min 0.0, :max 165.15}
 {:min 1676.0, :max 2752.800048828125}]


nil

## Off The Charts!

We take our processed dataset and our sequence of maps and output something called hiccup.  Hiccup really is HTML but encoded in clojure datastructures and keywords.  So you have a vector of intermixed more vectors and keywords.  Some strings.  And a few maps.

That is it, however.  That really is the absolute core of clojure.  A datastructure.  And powerful tools to go transform from one datastructure to another datastructure.  On top of this we can actually build anything.

But I Digress...


### Vega and Vega-lite


Now we get into Vega-lite.  This is documented library to make building graphs and charts using the vega visual language easier.  Vega is built on top of d3 and takes inspiration from libraries such as R's ggplot2 library. For more information on vega-lite, go [here](https://vega.github.io/vega-lite/).

We show all the features here because we are running out of time. The most important takeaway is that regardless of language you speak to vega (and vega-lite) in terms of datastructures.  

In [33]:
(defn duration->str
  [^Duration dur]
  (.toString dur))

(def chart-width 600)

(def view-ds [:div
              [:h2 (format "Behold - %s - %s"
                           (ds/dataset-name processed-ds)
                           (duration->str (ds-duration processed-ds)))]
              [:h3 "Dashboard"]
              [:vega-lite {:data {:values all-the-data}
                           :vconcat [{:projection {:type :albersUsa}
                                      :width chart-width
                                      :mark :circle
                                      :encoding {:latitude {:field (first lat-lon)
                                                            :type :quantitative}
                                                 :longitude {:field (second lat-lon)
                                                             :type :quantitative}
                                                 :color {:condition {:selection :times
                                                                     :field :altitude
                                                                     :type :quantitative
                                                                     :scale {:range [:darkblue :lightblue]}
                                                                    }
                                                         :value :lightgreen
                                                         }}}

                                     {:mark :point
                                      :width chart-width
                                      :selection {:times {:type :interval}}
                                      :encoding
                                      {:x {:field :minutes-from-start
                                           :type :quantitative
                                           :scale {:domain
                                                   [(:min minutes-range)
                                                    (:max minutes-range)]}}
                                       :y {:field :altitude
                                           :type :quantitative
                                           :scale {:domain [(:min altitude-data)
                                                            (:max altitude-data)]}}
                                       :color {:field :altitude
                                               :type :quantitative
                                               :scale {:range [:darkblue :lightblue]}}}}
                                     {:layer [{:mark :point
                                               :width chart-width
                                               :selection {:times {:type :interval}}
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :speed-mph
                                                              :type :quantitative}}}
                                              {:mark {:type :line
                                                      :color :yellow}
                                               :width chart-width
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :speed-avg
                                                              :type :quantitative}}}]}
                                     {:layer [{:mark :point
                                               :width chart-width
                                               :selection {:times {:type :interval}}
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :power
                                                              :type :quantitative}}}
                                              {:mark {:type :line
                                                      :color :yellow}
                                               :width chart-width
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :power-avg
                                                              :type :quantitative}}}]}
                                     {:layer [{:mark :point
                                               :width chart-width
                                               :selection {:times {:type :interval}}
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :cadence
                                                              :type :quantitative}}}
                                              {:mark {:type :line
                                                      :color :yellow}
                                               :width chart-width
                                               :encoding {:x {:field :minutes-from-start
                                                              :type :quantitative
                                                              :scale {:domain
                                                                      [(:min minutes-range)
                                                                       (:max minutes-range)]}}
                                                          :y {:field :cadence-avg
                                                              :type :quantitative}}}]}

                                     ]}]])

#'user/view-ds

In [26]:
(first view-ds)

:div

In [28]:
(second view-ds)

[:h2 "Behold - data/activities/81623728.fit.gz - PT2H45M9S"]

## And It Is Done!

Viewing the charts is simple.  And check it out--interactivity works!!  Selecting data on any of the scatter/line charts below will change the display of the geographic chart.

In [34]:
(oz/view! view-ds)

Behold - data/activities/81623728.fit.gz - PT2H45M9S Dashboard